// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZ6p61X5T8jmX1YfHLGbb-tdzR7wMDZQ',
    appId: '1:442438530938:web:3b3baa74f900ce213dc8c3',
    messagingSenderId: '442438530938',
    projectId: 'cash-calculator-847c1',
    authDomain: 'cash-calculator-847c1.firebaseapp.com',
    storageBucket: 'cash-calculator-847c1.appspot.com',
    measurementId: 'G-EFVE61JXPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOJuwKr832djcqLkBGnjOSnK4tAgNkHc',
    appId: '1:442438530938:android:47d4d05a4bf887253dc8c3',
    messagingSenderId: '442438530938',
    projectId: 'cash-calculator-847c1',
    storageBucket: 'cash-calculator-847c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMaJ7ipuFPNAKdnO1pnDC9gpqNCpmmWo',
    appId: '1:442438530938:ios:2eb86012c861879d3dc8c3',
    messagingSenderId: '442438530938',
    projectId: 'cash-calculator-847c1',
    storageBucket: 'cash-calculator-847c1.appspot.com',
    iosBundleId: 'com.example.cashcalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCMaJ7ipuFPNAKdnO1pnDC9gpqNCpmmWo',
    appId: '1:442438530938:ios:5b4339eba67c1e3b3dc8c3',
    messagingSenderId: '442438530938',
    projectId: 'cash-calculator-847c1',
    storageBucket: 'cash-calculator-847c1.appspot.com',
    iosBundleId: 'com.example.cashcalculator.RunnerTests',
  );
}
